### ISSUE TITLE
libsepol: ibpkeys.c: compiling error on Fedora 28 armv7l

### ISSUE THREAD

**Issue by aIecxs** [SELinuxProject/selinux#108]
I am not sure if this is an code issue or just wrong build environment setup, but i get the same error in Ubuntu 18.04 and Fedora 28 running on ARM device. How to fix makefile?

`cc -O2 -Werror -Wall -Wextra -Wmissing-format-attribute -Wmissing-noreturn -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -I/home/fedora/obj/usr/include -I. -I../include -D_GNU_SOURCE -I../cil/include -fPIC -c -o ibpkeys.o ibpkeys.c
In file included from ibpkeys.c:4:
ibpkeys.c: In function 'sepol_ibpkey_query':
ibpkeys.c:179:14: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
  ERR(handle, "could not query ibpkey subnet prefix: %#lx range %u - %u exists",
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      subnet_prefix, low, high);
      ~~~~~~~~~~~~~
debug.h:46:15: note: in definition of macro 'msg_write'
     _sepol_h, __VA_ARGS__);     \
               ^~~~~~~~~~~
ibpkeys.c:179:2: note: in expansion of macro 'ERR'
  ERR(handle, "could not query ibpkey subnet prefix: %#lx range %u - %u exists",
  ^~~
ibpkeys.c: In function 'sepol_ibpkey_modify':
ibpkeys.c:206:14: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
  ERR(handle, "could not load ibpkey subnet prefix: %#lx range %u - %u exists",
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      subnet_prefix, low, high);
      ~~~~~~~~~~~~~
debug.h:46:15: note: in definition of macro 'msg_write'
     _sepol_h, __VA_ARGS__);     \
               ^~~~~~~~~~~
ibpkeys.c:206:2: note: in expansion of macro 'ERR'
  ERR(handle, "could not load ibpkey subnet prefix: %#lx range %u - %u exists",
  ^~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:76: ibpkeys.o] Error 1
make[2]: Leaving directory '/home/fedora/src/selinux/libsepol/src'
make[1]: *** [Makefile:6: all] Error 2
make[1]: Leaving directory '/home/fedora/src/selinux/libsepol'
make: *** [Makefile:34: all] Error 1
[fedora@localhost selinux]$ `

**Comment by stephensmalley** [comment]
See if the referenced PR fixes this for you.

**Comment by aIecxs** [comment]
confirmed. it is compiling successful now, except for a simple warning. many thanks!
`../cil/src/cil_lexer.c: In function ‘cil_yy_scan_bytes’:
../cil/src/cil_lexer.c:1595:17: warning: comparison of integer expressions of different signedness: ‘yy_size_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
  for ( i = 0; i < _yybytes_len; ++i )
                 ^
`

**Comment by aIecxs** [comment]
now i have some other issues, maybe you can also fix?

libselinux: selinux_restorecon.c: compiling error on Fedora 28 armv7l
`selinux_restorecon.c: In function ‘restorecon_sb’:
selinux_restorecon.c:633:26: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]
     fprintf(stdout, "\r%luk", fc_count / STAR_COUNT);
                        ~~^
                        %llu
`

checkpolicy: checkpolicy.c: compiling error on Fedora 28 armv7l
compiles with -Wno-error=implicit-function-declaration -Wno-error=sign-compare but error persists
`checkpolicy.c: In function ‘main’:
checkpolicy.c:498:20: error: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘long int’ [-Werror=sign-compare]
     if (policyvers != n)
                    ^~
checkpolicy.c:645:12: error: implicit declaration of function ‘policydb_sort_ocontexts’; did you mean ‘policydb_user_cache’? [-Werror=implicit-function-declaration]
      ret = policydb_sort_ocontexts(&policydb);
            ^~~~~~~~~~~~~~~~~~~~~~~
            policydb_user_cache
checkpolicy.o: In function `main':
checkpolicy.c:(.text.startup+0x5e8): undefined reference to `policydb_sort_ocontexts'
collect2: error: ld returned 1 exit status
`

policycoreutils: semodule.c: compiling error on Fedora 28 armv7l
i have checked owner/permissions, compiles with -I~/src/selinux/libsemanage/include -L~/src/selinux/libsemanage/src but error persists
`semodule.c:25:10: fatal error: semanage/modules.h: No such file or directory
 #include <semanage/modules.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
/usr/bin/ld: cannot find -lsemanage
collect2: error: ld returned 1 exit status
`

**Comment by aIecxs** [comment]
can be closed. seems i have messed up something. after fresh install Fedora 28 armv7l it works. it was my fault i was using export DESTDIR='~/obj' instead of DESTDIR=~/obj - apologizing :)

just for unskilled users like me, here is what i have done: (Note: setools-devel was not available)
`sudo -H yum install automake gcc gettext-devel git glibc-static libacl-devel libffi-devel make pcre-static perl-Pod-Html wget
sudo -H yum install audit-libs-devel bison bzip2-devel dbus-devel dbus-glib-devel flex flex-devel flex-static glib2-devel libcap-devel libcap-ng-devel pam-devel pcre-devel python-devel setools swig xmlto redhat-rpm-config

git clone https://github.com/SELinuxProject/selinux.git

mkdir ~/obj
export DESTDIR=~/obj
export CFLAGS="-I/usr/include -I/usr/local/include -I${DESTDIR}/usr/include"
export LDFLAGS="-L/usr/lib -L/usr/local/lib -L${DESTDIR}/lib -L${DESTDIR}/usr/lib"

make install install-pywrap`
