### ISSUE TITLE
restorecond doesn't need pcre

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/selinux#137]
Hi,

Any reasons why restorecond is being linked against libpcre?

AFAICS it's not using any symbols from that library

**Comment by stephensmalley** [comment]
Probably unnecessary, indirect dependency via libselinux.

**Comment by bigon** [comment]
What I mean is that it's explicitly liking against it: https://github.com/SELinuxProject/selinux/blob/master/restorecond/Makefile#L22
