### ISSUE TITLE
SELinux depends on the internal structure of glibc

### ISSUE THREAD

**Issue by samiam95124** [SELinuxProject/selinux#150]
Hello, my name is Scott Franco, I am currently using alternatives to glibc for embedded purposes.
While debugging a program using GTK+, I found out (the hard way) that selinux is poking around in the internal structure of glibc FILE stucture types. This, of course, causes a segfault in libc implementations that are NOT glibc.

Points:

1. This is an ugly defacto dependency on glibc. The makers of glibc (and indeed the libc infrastructure in general, which goes back to the beginnings of Unix) worked hard to present an API abstraction that is general purpose, and is in fact implemented in many different libcs. At a stroke, selinux abrogates that abstraction.

2. It is widespread. I found selinux pulled in by GTK+, a common toolkit in wide use. I don't doubt that it appears linked in to many other programs or pulled in as part of a library.

3. It is a deep penetration of the internals of glibc. In fact, you have to get the source for glibc and look down several levels to struct_FILE.h to find it. This is not a light incursion to another program, but a deep link into obscure details of another program. The selinux mentions the use of a "independent wrapper" to access those internals, but nowhere in that code is any attempt made to actually VERIFY that glibc is giving that data structure (nor is it probably possible.. the FILE structure does not have such identifying information).

Was this code diving into the internals of glibc REALLY necessary? I suggest some thought about this.

The upshot is I am now attempting to make my FILE structure format LOOK like glibc just to please selinux. What a nasty outcome.

Scott Franco
San Jose, CA

**Comment by stephensmalley** [comment]
Can you identify the specific source code in question?

**Comment by samiamewerks** [comment]
libselinux/src/init.c:64:	fp = fopen("/proc/filesystems", "re");

int selinuxfs_exists(void)
{
	int exists = 0;
	FILE *fp = NULL;
	char *buf = NULL;
	size_t len;
	ssize_t num;

	fp = fopen("/proc/filesystems", "re");
	if (!fp)
		return 1; /* Fail as if it exists */
	__fsetlocking(fp, FSETLOCKING_BYCALLER);
...

__fsetlocking(...) is the function diving into the FILE* structure.  However, note that this is just the first
such instance I hit (resulting in segfault).

and.....

__fsetlocking is a standard glibc function, meaning that if it is a backdoor, its a "standardized" one. Apologies, I should have looked further before commenting. I'll mark this as closed.

My issue will (apparently) be solved by implementing my version of __fsetlocking(). Lesson learned.

**Comment by samiam95124** [comment]
So just as an afternote (and perhaps prove I am not completely stupid), I implemented everything in stdio.h (fopen, fclose, etc) which defines "whitebook C". __fsetlocking is not defined there, and indeed, it was apparently introduced by SUN as a extension. As I think selinux (and probably others) demonstrate, calling that an extension and putting it elsewhere than stdio.h does not make it transparent, since it creates a dependency, and perhaps worse, one outside of whitebook C and thus not as well documented.

**Comment by stephensmalley** [comment]
Looking back into the code history (before git), the patches first introducing the usage of __fsetlocking were from Ulrich Drepper, glibc maintainer at the time (2005).  Not the sort of thing we would have likely done on our own.  I think I had to strip these calls from the Android fork for a bit until bionic grew __fsetlocking support for other reasons.  Omitting the call or turning it into a no-op is harmless of course; it is just an optimization.

**Comment by samiam95124** [comment]
For grins I looked at another typical embedded systems stdio implementation, newlib. It also implements a version of fsetlocking, so others have encountered this before. The existence of the function is (believe it or not) actually a positive thing, I thought I would have to make my FILE* structure look like glibc, which I would rather not. This allows me to use my own formats internally. 

Pretty impressive you could look that up. I don't offhand have an opinion as to if you should remove it.
