### ISSUE TITLE
sandbox -i fails on files accessible to user but with context not accessible to sandbox program

### ISSUE THREAD

**Issue by mikedlr** [SELinuxProject/selinux#16]
What did you do?
```
cd
sandbox -X -i myfile2.doc xdg-open myfile2.doc
```

What happened?
`xdg-open: no permission to read file '/home/mikedlr/myfile2.doc'`

What did you expect to happen?
Sandbox should open the file - I'd normally expect that if I am allowed to use a file, then I should be allowed to use it in a sandbox which should _always_ be a more restricted environment than the one that I am currently in.  

Any other information:
```
$ ls -Z myfile2.doc 
unconfined_u:object_r:user_home_t:s0 myfile2.doc
```

This is running on a fedora23 more or less default install.  The package with the failing sandbox is _policycoreutils-2.4-21.fc23.x86_64_

I'm putting this in as an upstream report of https://bugzilla.redhat.com//show_bug.cgi?id=1317046 for use in a pull request,  I intend to attempt to patch this and then, succeed or fail, report the situation to the mailing list.

**Comment by stephensmalley** [comment]
Fixed by commit 964bf69a653820ed704e0f2cefbb88f354c9c393 ("sandbox: fix file labels on copied files").  Red Hat bug https://bugzilla.redhat.com/show_bug.cgi?id=1294020
