### ISSUE TITLE
libsepol 2.9: test suite build fails

### ISSUE THREAD

**Issue by kloczek** [SELinuxProject/selinux#166]
<pre>+ /usr/bin/make -O -j48 test
/usr/bin/make -C tests test
make[1]: *** No rule to make target &apos;../../checkpolicy/queue.o&apos;, needed by &apos;libsepol-tests&apos;.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-linker-types.o test-linker-types.c
test-linker-types.c:22:10: fatal error: parse_util.h: No such file or directory
   22 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-linker-types.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-linker-roles.o test-linker-roles.c
test-linker-roles.c:21:10: fatal error: parse_util.h: No such file or directory
   21 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-linker-roles.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-linker-cond-map.o test-linker-cond-map.c
test-linker-cond-map.c:21:10: fatal error: parse_util.h: No such file or directory
   21 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-linker-cond-map.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o helpers.o helpers.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../include/sepol/policydb/policydb.h:54,
                 from helpers.h:25,
                 from helpers.c:24:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
helpers.c:25:10: fatal error: parse_util.h: No such file or directory
   25 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [&lt;builtin&gt;: helpers.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-cond.o test-cond.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /usr/include/CUnit/CUnit.h:53,
                 from /usr/include/CUnit/Basic.h:36,
                 from test-cond.h:24,
                 from test-cond.c:21:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
test-cond.c:22:10: fatal error: parse_util.h: No such file or directory
   22 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-cond.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-linker.o test-linker.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /usr/include/CUnit/CUnit.h:53,
                 from /usr/include/CUnit/Basic.h:36,
                 from test-linker.h:24,
                 from test-linker.c:29:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
test-linker.c:30:10: fatal error: parse_util.h: No such file or directory
   30 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-linker.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-expander.o test-expander.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /usr/include/CUnit/CUnit.h:53,
                 from /usr/include/CUnit/Basic.h:36,
                 from test-expander.h:24,
                 from test-expander.c:33:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
test-expander.c:34:10: fatal error: parse_util.h: No such file or directory
   34 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-expander.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-deps.o test-deps.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /usr/include/CUnit/CUnit.h:53,
                 from /usr/include/CUnit/Basic.h:36,
                 from test-deps.h:24,
                 from test-deps.c:21:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
test-deps.c:22:10: fatal error: parse_util.h: No such file or directory
   22 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-deps.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-downgrade.o test-downgrade.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /usr/include/CUnit/CUnit.h:53,
                 from /usr/include/CUnit/Basic.h:36,
                 from test-downgrade.h:24,
                 from test-downgrade.c:21:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
test-downgrade.c:22:10: fatal error: parse_util.h: No such file or directory
   22 | #include &quot;parse_util.h&quot;
      |          ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [&lt;builtin&gt;: test-downgrade.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o debug.o debug.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../include/sepol/policydb/policydb.h:54,
                 from debug.h:23,
                 from debug.c:23:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [&lt;builtin&gt;: debug.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-expander-attr-map.o test-expander-attr-map.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../include/sepol/policydb/policydb.h:54,
                 from test-common.h:25,
                 from test-expander-attr-map.c:23:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [&lt;builtin&gt;: test-expander-attr-map.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o libsepol-tests.o libsepol-tests.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from /usr/include/CUnit/CUnit.h:53,
                 from /usr/include/CUnit/Basic.h:36,
                 from test-cond.h:24,
                 from libsepol-tests.c:21:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [&lt;builtin&gt;: libsepol-tests.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-expander-roles.o test-expander-roles.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../include/sepol/policydb/policydb.h:54,
                 from test-common.h:25,
                 from test-expander-roles.c:24:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [&lt;builtin&gt;: test-expander-roles.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-expander-users.o test-expander-users.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../include/sepol/policydb/policydb.h:54,
                 from test-expander-users.c:25:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [&lt;builtin&gt;: test-expander-users.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Os -g3 -gdwarf-2 -O0 -Wall -W -Wundef -Wmissing-noreturn -Wmissing-format-attribute -Wno-unused-parameter -Werror -I../include/ -I../../checkpolicy/  -c -o test-common.o test-common.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from ../include/sepol/policydb/policydb.h:54,
                 from ../include/sepol/policydb/avrule_block.h:23,
                 from test-common.c:25:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [&lt;builtin&gt;: test-common.o] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libsepol-2.9/tests&apos;
make: *** [Makefile:29: test] Error 2
</pre>

**Comment by fishilico** [comment]
Hello,
libsepol's testsuite relies on some files from checkpolicy (cf. https://github.com/SELinuxProject/selinux/blob/libsepol-2.9/libsepol/tests/Makefile#L19-L21). It has been designed in order to detect regressions during development, which is why it expects checkpolicy's source code to be present in a directory named `checkpolicy` next to `libsepol`.

Nevertheless this behavior is the "behavior by default" which is used when running `make test` from the root directory of this project. It can be modified to use `checkpolicy` source code from some other places using the build variable `CHECKPOLICY`. This way, you should be able to run tests from the released tarball.

**Comment by kloczek** [comment]
OK. Will try to adapt my  build procedure.
Thank you.
