### ISSUE TITLE
libselinux 2.9: does not build

### ISSUE THREAD

**Issue by kloczek** [SELinuxProject/selinux#167]
```
gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I../include -D_GNU_SOURCE -DDISABLE_RPM -DNO_ANDROID_BACKEND -DUSE_PCRE2 -DPCRE2_CODE_UNIT_WIDTH=8   -c -o procattr.o procattr.c
procattr.c:38:14: error: static declaration of 'gettid' follows non-static declaration
   38 | static pid_t gettid(void)
      |              ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from procattr.c:2:
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make[1]: *** [Makefile:171: procattr.o] Error 1
```

**Comment by fishilico** [comment]
Hello,
Which libc are you using? (for example "glibc 2.29"). The code tries to detect it in order to know whether it should declare a wrapper for `gettid` system call or not, and this detection appears to fail on your system: https://github.com/SELinuxProject/selinux/blob/libsepol-2.9/libselinux/src/procattr.c#L25-L35

**Comment by kloczek** [comment]
glibc-2.29.9000-28.fc31.x86_64 from Fedora.

**Comment by bachradsusi** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1685594
In Fedora I fixed it using temporary downstream patch https://github.com/fedora-selinux/selinux/commit/431f72836d6c02450725cf6ffb1c7223b9fa6acc which allows to control whether or not override gettid() - https://src.fedoraproject.org/rpms/libselinux/blob/f3c6251fc2100c809b1f7db0482881d3ddcd1228/f/libselinux.spec#_109

**Comment by bachradsusi** [comment]
The problem should disappear with https://fedoraproject.org/wiki/Changes/GLIBC230
