### ISSUE TITLE
Libsepol uses cdefs which will cause compiling against anything but glibc to fail.

### ISSUE THREAD

**Issue by ratbert90** [SELinuxProject/selinux#19]
Libsepol uses cdefs.h which is a internal glibc header.
 This header is not intended to be used by any program and will cause
 compiling against musl (and possibly other c libraries) to fail.
 This patch fixed this issue and replaces all references of
 #include <sys/cdefs.h> and __BEGIN/END_DECLS with the appropriate #ifdefs.

[libsepol-remove-cdefs-references.patch.zip](https://github.com/SELinuxProject/selinux/files/354554/libsepol-remove-cdefs-references.patch.zip)

**Comment by stephensmalley** [comment]
Submit to selinux AT tycho.nsa.gov

**Comment by williamcroberts** [comment]
ratbert90 I don't see this submitted to the mailing list, if you would like it reviewed, please submit a patch to the mailing list. Instructions can be found here: https://www.nsa.gov/what-we-do/research/selinux/mailing-list.shtml
