### ISSUE TITLE
Please port mcstrans to pcre2

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/selinux#194]
Hello,

It seems that mcstrans is the only component still using pcre(1) instead of pcre2

That should probably be ported to pcre2 as well

**Comment by bigon** [comment]
FTR: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000055

**Comment by fishilico** [comment]
This task was done in https://github.com/SELinuxProject/selinux/commit/647909cb90e0230d99b0d9c0a09afcfbecc452e2 and released in 3.4
