### ISSUE TITLE
 please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [SELinuxProject/selinux#198]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:

* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:

* For github and gitlab hosted projects, Weblate open pull request. For other git hosting, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

Concerned project: https://fedora.zanata.org/project/view/selinux

**Comment by bachradsusi** [comment]
This repository doesn't use Zanata. The correct repository according to zanata project home page is https://github.com/fedora-selinux/selinux - https://github.com/fedora-selinux/selinux/issues/59

**Comment by Jibec** [comment]
Thank you for moving this issue, but I'm unsure what to do here. I know 
Fedora mindset is: upstream first.

As this is a dedicated project for fedora, it probably means there is 
good reasons for this.

But should we do the same for translations?

To content really looks the same to me:
https://github.com/SELinuxProject/selinux/tree/master/policycoreutils/po
https://github.com/fedora-selinux/selinux/tree/master/policycoreutils/po

If you, as upstream project would like us to host your project, I'll 
migrate the Zanata project to Weblate.
If you don't would like to do it, then I'll just ask the Zanata project 
to be locked.

If you expect distribution specific selinux projects to have specific 
content to translate, we can host both.

What makes sense for you?

**Comment by bachradsusi** [comment]
The problem with translations is that they generate big patches. In Fedora we don't patch the repository directly but we create tarball from downloaded translations from Zanata, and use them during build, see https://src.fedoraproject.org/rpms/policycoreutils/blob/master/f/README.translations Also we split translation in Fedora into subproject to follow the directory and release tarballs structure.

In this project, the translations haven't been updated for several releases, there are just minor type fixes. It needs to be reconsidered and this discussion should happen on SELinux mailing list - selinux@vger.kernel.org.

**Comment by bachradsusi** [comment]
So my suggestion is to migrate fedora-selinux/selinux project (which uses https://fedora.zanata.org/project/view/selinux) first, and then start a discussion  about translation in this project on its mailling list

**Comment by Jibec** [comment]
Yes, this is a common issue for big projects.
I suggest you to follow what other big projects do: a dedicated 
translation repository.
 From there, either you take the translation and commit it in your repo 
or just include it with your releases.

One example: https://github.com/cockpit-project/cockpit/issues/13319

**Comment by vmojzis** [comment]
@Jibec Is there any advantage in having a dedicated translation repository if we only intend to include the translations with our releases (and not store them in the source repository)? I was thinking of just using weblate client to download the latest translations when we need them (as opposed to having it push updates to a dedicated repository).

**Comment by Jibec** [comment]
weblate requires to be informed a new version of pot file is available for translation.

either you commit it in your repository and you don't need a dedicated l10n repo, either you create an l10n repo.
if you create an l10n repo, giving write access for weblate is not an issue.

keep it simple, create an l10n repo, it will make everything easier. Newcomers will understand easily how to contribute, and you'll be able yo measure contribution. 

please hurry your migration, Zanata will be totally removed in a month.
--
Jean-Baptiste

**Comment by bachradsusi** [comment]
I don't get it. Why we need a new repo when weblate is able to use .pots file from our existing repo and we can download translations from weblate?

**Comment by bachradsusi** [comment]
Anyway, this discussion should be in https://github.com/fedora-selinux/selinux/issues/59

**Comment by Jibec** [comment]
you have a specific way of organizing your repositories that I don't understand, and you didn't explain how you work.

Fedora contribute upstream.
If fedora-selinux is a fork of selinux project with specific Fedora rules, then there is no translation to do in Fedora-selinux and adding all to selinux directly.

If for some reasons, the fork is the only way to do, then we could add both to the translation platform, so that translators contribute both projects (Weblate handles this nicely).

Fedora moved to Weblate, Zanata will stop.
Weblate have a specific behavior which provides nice and easy integration with git repositories and translators.
I suggest you to keep it simple, include translations in your code.

You want smaller patches? I can remove line numbers in po files, saving a lot in diffs.
You want less commits? We can use git squash.
You want signoff? We can add this too.

You don't want translators contribution in your repository and/or your github organization?
Well, why do allow translation at all?

Note it looks like selinux:

* uses (or used?) Transifex: https://github.com/SELinuxProject/selinux/blob/master/policycoreutils/.tx/config
* could gain translation of manpages using po4a: https://github.com/SELinuxProject/selinux/commit/e3e3873de72e2dbb5d9079fc5d57c8267dea8986
* don't have the same list of po files has fedora-selinux

why should each distribution have to translate the same thing?

**Comment by bachradsusi** [comment]
https://github.com/SELinuxProject/selinux/issues/198#issuecomment-574057743 and https://github.com/SELinuxProject/selinux/issues/198#issuecomment-674916289 are still valid. I'm willing to implement/propose/update/maintain translations in this repository later when it's implemented for fedora-selinux/selinux and when it's clear how it works.
