### ISSUE TITLE
avcstat.c:206]: (style) Redundant condition

### ISSUE THREAD

**Issue by dcb314** [SELinuxProject/selinux#20]
avcstat.c:206]: (style) Redundant condition: !cumulative. 'cumulative || (!cumulative && !i)' is equivalent to 'cumulative || !i'

Source code is

```
   if (cumulative || (!cumulative && !i))
```

**Comment by stephensmalley** [comment]
Yes, want to send a patch to selinux AT tycho.nsa.gov?
