### ISSUE TITLE
empty policy files after power outage during semanage fcontext

### ISSUE THREAD

**Issue by tomash655** [SELinuxProject/selinux#237]
Hi,

I've experienced a bug which occurs when running "semanage fcontext -a -t <type> <file>". this command takes about 2-3 seconds, and if a force shutdown is happening at that time, the server fails to boot with the error "Failed to load selinux policy, freezing". After starting the server with "selinux=0", I noticed that both /etc/selinux/targeted/policy/policy.31 and all the files under /etc/selinux/targeted/active/modules/100 are empty, which are probably the reason for this error.

Of course, after reinstalling selinux-policy-targeted and relabeling the filesystem using /.autorelabel, everything is fine.

Anyway, I successfully reproduce this by running semanage fcontext on some files and force shutdown the server, so my guess is that there are some unsafe writes there.

I'm using CentOS 7.6 by the way.

**Comment by stephensmalley** [comment]
libsemanage version?

**Comment by stephensmalley** [comment]
Looks like it needs a fsync(2) before rename(2).

**Comment by tomash655** [comment]
libsemanage-2.5-14.el7.x86_64

I have a code which runs a bunch of `semanage fcontext` commands and so I added `sync` at the end to reduce the possibility of that happening. Also, when I added the `-N` It did not reproduced, so I run it on multiple files, then I reloaded the policy and then I added the sync command at the end.

Hope you can resolve this issue.

**Comment by stephensmalley** [comment]
Recommend opening a bug on Red Hat's bugzilla if you want a fix for el7.

**Comment by tomash655** [comment]
In cases someone encountering this issue:

**Comment by stephensmalley** [comment]
You can try the fix here https://github.com/stephensmalley/selinux/commit/4d9552d6f3166ecb85eb5b808b6a8ffe7f212360
if it applies to the el7 sources.

**Comment by stephensmalley** [comment]
Discussion of this patch is happening here: https://lore.kernel.org/selinux/CAEjxPJ6U4vx+OB8WD689Vki1jVLeBzOgfgMawhbsT-KCXVn-WQ@mail.gmail.com/T/#t

**Comment by stephensmalley** [comment]
v2 here: https://github.com/stephensmalley/selinux/commit/f8c865328c4cbf9b254095441f962707df81b084, discussion here: https://lore.kernel.org/selinux/5ebc4bc6.1c69fb81.a8850.464e@mx.google.com/T/#u
