### ISSUE TITLE
setfiles: rootpath logic breaks on absolute symlinks

### ISSUE THREAD

**Issue by lucab** [SELinuxProject/selinux#248]
This is a followup from https://github.com/coreos/fedora-coreos-tracker/issues/512.

This affects the latest released version, as packaged in Fedora (package NEVRA is `policycoreutils-3.0-2.module_f32+7989+651e8914.x86_64`).

When using the `-r` logic to relabel files under a different rootpath, symlinks to absolute paths seem to break the relabeling logic:
```
# mkdir /root/my-chroot && echo foo > /root/my-chroot/link-target && ln -s /link-target /root/my-chroot/symlink
# echo "/root/my-chroot/symlink" | setfiles -vFi -r /root/my-chroot -f - /etc/selinux/targeted/contexts/files/file_contexts
setfiles: statfs(/root/my-chroot/symlink) failed: No such file or directory
```

However, from the point of view of the new rootpath, paths and symlinks are setup properly:
```
# cp -a --preserve=context /usr/local/bin/busybox-sh /root/my-chroot/
# chroot /root/my-chroot/ /busybox-sh cat /symlink
foo
```

So this sounds like a bug in `setfiles` relabeling logic.

**Comment by stephensmalley** [comment]
Regression introduced by e016502c0a265d661a3a4b541b865eec94aae2b1

**Comment by jlebon** [comment]
Related: https://lore.kernel.org/selinux/20200604191240.263819-1-jlebon@redhat.com/T/#u

**Comment by stephensmalley** [comment]
Possible fix: https://lore.kernel.org/selinux/20200604200831.28866-1-stephen.smalley.work@gmail.com/T/#u
