### ISSUE TITLE
Cannot send a packet with categories

### ISSUE THREAD

**Issue by Arnoldream** [SELinuxProject/selinux#252]
pc1：192.168.3.3
netlabelctl cipsov4 add trans doi:8 tags:1 levels:0=1 categories:0=1,1=2
netlabelctl map del default
netlabelctl map add default address:192.168.3.5 protocol:cipsov4,8
runcon "root:object_r:unlabeled_t:s0-s0:c1" "/root/misc-getpeercon_server/src/getpeercon_server" 8888
pc2：192.168.3.5
netlabelctl cipsov4 add trans doi:8 tags:1 levels:0=1 categories:0=1,1=2
netlabelctl map del default
netlabelctl map add default address:192.168.3.3 protocol:cipsov4,8
runcon "system_u:object_r:bin_t:s0-s0:c1" "/usr/bin/telnet" 192.168.3.3 8888
[root@localhost src]# sestatus
SELinux status:                     enabled
SELinuxfs mount:                 /sys/fs/selinux
SELinux root directory:        /etc/selinux
Loaded policy name:           mls
Current mode:                     permissive
Mode from config file:        permissive
Policy MLS status:               enabled
Policy deny_unknown status:     denied
Max kernel policy version:      31

**Comment by stephensmalley** [comment]
This repository is for the selinux userspace (libsepol, libselinux, ...) not for the kernel or netlabelctl.  Report bugs to the selinux mailing list, selinux@vger.kernel.org, and include information about your kernel. http://vger.kernel.org/vger-lists.html#selinux

**Comment by stephensmalley** [comment]
Also, for reference, a set of tests for CIPSO labeling across a network can be found at: https://patchwork.kernel.org/patch/11498941/
This is a patch on top of the selinux testsuite, https://github.com/SELinuxProject/selinux-testsuite, which currently only exercises it over loopback.

**Comment by Arnoldream** [comment]
Thank you for your answer
