### ISSUE TITLE
Fails to build on non-selinux systems. [patch]

### ISSUE THREAD

**Issue by lockywolf** [SELinuxProject/selinux#258]
Hello, friends.

The code fails on non-selinux systems.

I have a patch
[build-patch.patch.txt](https://github.com/SELinuxProject/selinux/files/5006908/build-patch.patch.txt)

Feel free to use it.

**Comment by stephensmalley** [comment]
Building as per the README should work fine even on non-SELinux, e.g. make DESTDIR=~/obj install from top-level to build and install to a private tree, or  make LIBDIR=/usr/lib64 SHLIBDIR=/lib64 install relabel from top-level to build and install into system directories (potentially overwriting any previously installed ones).  Distributions actually package up the components separately (e.g. libselinux, libsepol, ...) so cross-component references are discouraged. Patches should be sent via git-send-email with Signed-off-by line to selinux mailing list.
