### ISSUE TITLE
Build failure with musl 1.2.2

### ISSUE THREAD

**Issue by ffontaine** [SELinuxProject/selinux#282]
Since version 1.2.2, musl (which does not define `__GLIBC_PREREQ`) now implements gettid. As result, build fails on:

```
procattr.c:38:14: error: static declaration of 'gettid' follows non-static declaration
   38 | static pid_t gettid(void)
      |              ^~~~~~
In file included from procattr.c:2:
/home/buildroot/autobuild/instance-1/output-1/host/arm-buildroot-linux-musleabihf/sysroot/usr/include/unistd.h:194:7: note: previous declaration of 'gettid' was here
  194 | pid_t gettid(void);
      |       ^~~~~~
```

I don't know how to fix it cleanly (without breaking the code with "old" musl that is).

Full build log: http://autobuild.buildroot.org/results/9db/9db956595a1ddfb7ed5d1879d9a98252b07deb52/build-end.log

**Comment by bigon** [comment]
FTR, there was a patch proposed in [debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989748) that was adding some kind of detection
