### ISSUE TITLE
selinuxenabled man page doesn't mention permissive mode

### ISSUE THREAD

**Issue by sebastian-philipp** [SELinuxProject/selinux#283]
The man page of doesn't mention the exit status, if selinux is in permissive mode:

https://github.com/SELinuxProject/selinux/blob/e8bcdb84dc0937b65ca1e9167b436b21375b96ab/libselinux/man/man8/selinuxenabled.8#L11-L12

Would be great to get that information from the man page.

**Comment by bachradsusi** [comment]
If SELinux is in permissive mode it's enabled and `selinuxenabled` returns 0.

If you need to check whether SELinux is permissive or enforcing use `getenforce`
