### ISSUE TITLE
All processes are labeled with same security context (kernel_t)?

### ISSUE THREAD

**Issue by cxdinter** [SELinuxProject/selinux#301]
Hi ,
I am trying to porting SELinux into the iMX6 Linux system. Now, it seems SELinux is working, but all process are labeled with same security context - system_u:system_r:kernel_t:s15:c0.c1023. I don't know why? Why the process' label is not the one which I defined in file_contexts??
Please kindly give me some guide, thank you.

root@ccx:~# ps -efZ
LABEL                           UID        PID  PPID  C STIME TTY          TIME CMD
system_u:system_r:kernel_t:s15:c0.c1023 root 1     0  0 Jun30 ?        00:00:02 init [5]
system_u:system_r:kernel_t:s15:c0.c1023 root 2     0  0 Jun30 ?        00:00:00 [kthreadd]
system_u:system_r:kernel_t:s15:c0.c1023 root 3     2  0 Jun30 ?        00:00:00 [ksoftirqd/0]
system_u:system_r:kernel_t:s15:c0.c1023 root 4     2  0 Jun30 ?        00:00:00 [kworker/0:0]
system_u:system_r:kernel_t:s15:c0.c1023 root 5     2  0 Jun30 ?        00:00:00 [kworker/0:0H]
system_u:system_r:kernel_t:s15:c0.c1023 root 6     2  0 Jun30 ?        00:00:00 [kworker/u4:0]
system_u:system_r:kernel_t:s15:c0.c1023 root 7     2  0 Jun30 ?        00:00:00 [rcu_preempt]
system_u:system_r:kernel_t:s15:c0.c1023 root 8     2  0 Jun30 ?        00:00:00 [rcu_sched]
system_u:system_r:kernel_t:s15:c0.c1023 root 9     2  0 Jun30 ?        00:00:00 [rcu_bh]
system_u:system_r:kernel_t:s15:c0.c1023 root 10    2  0 Jun30 ?        00:00:00 [migration/0]
system_u:system_r:kernel_t:s15:c0.c1023 root 11    2  0 Jun30 ?        00:00:00 [khelper]
system_u:system_r:kernel_t:s15:c0.c1023 root 12    2  0 Jun30 ?        00:00:00 [kdevtmpfs]
system_u:system_r:kernel_t:s15:c0.c1023 root 13    2  0 Jun30 ?        00:00:00 [kworker/u4:1]
system_u:system_r:kernel_t:s15:c0.c1023 root 14    2  0 Jun30 ?        00:00:00 [perf]
system_u:system_r:kernel_t:s15:c0.c1023 root 269   2  0 Jun30 ?        00:00:00 [writeback]
system_u:system_r:kernel_t:s15:c0.c1023 root 271   2  0 Jun30 ?        00:00:00 [crypto]
system_u:system_r:kernel_t:s15:c0.c1023 root 272   2  0 Jun30 ?        00:00:00 [bioset]
system_u:system_r:kernel_t:s15:c0.c1023 root 274   2  0 Jun30 ?        00:00:00 [kblockd]
system_u:system_r:kernel_t:s15:c0.c1023 root 316   2  0 Jun30 ?        00:00:00 [ipu1_task]
system_u:system_r:kernel_t:s15:c0.c1023 root 317   2  0 Jun30 ?        00:00:00 [ipu1_task]
system_u:system_r:kernel_t:s15:c0.c1023 root 409   2  0 Jun30 ?        00:00:00 [kworker/0:1]
system_u:system_r:kernel_t:s15:c0.c1023 root 424   2  0 Jun30 ?        00:00:00 [kswapd0]
system_u:system_r:kernel_t:s15:c0.c1023 root 474   2  0 Jun30 ?        00:00:00 [fsnotify_mark]
system_u:system_r:kernel_t:s15:c0.c1023 root 620   2  0 Jun30 ?        00:00:01 [spi0]
system_u:system_r:kernel_t:s15:c0.c1023 root 634   2  0 Jun30 ?        00:00:00 [ci_otg]
system_u:system_r:kernel_t:s15:c0.c1023 root 654   2  0 Jun30 ?        00:00:00 [vpu_wq]
system_u:system_r:kernel_t:s15:c0.c1023 root 657   2  0 Jun30 ?        00:00:00 [galcore workque]
system_u:system_r:kernel_t:s15:c0.c1023 root 658   2  0 Jun30 ?        00:00:00 [galcore daemon ]
system_u:system_r:kernel_t:s15:c0.c1023 root 659   2  0 Jun30 ?        00:00:00 [galcore daemon ]
system_u:system_r:kernel_t:s15:c0.c1023 root 718   2  0 Jun30 ?        00:00:00 [deferwq]
system_u:system_r:kernel_t:s15:c0.c1023 root 719   2  0 Jun30 ?        00:00:00 [kworker/u4:2]
system_u:system_r:kernel_t:s15:c0.c1023 root 720   2  0 Jun30 ?        00:00:00 [irq/273-imx_the]
system_u:system_r:kernel_t:s15:c0.c1023 root 727   2  0 Jun30 ?        00:00:00 [ubi_bgt0d]
system_u:system_r:kernel_t:s15:c0.c1023 root 736   2  0 Jun30 ?        00:00:00 [migration/1]
system_u:system_r:kernel_t:s15:c0.c1023 root 737   2  0 Jun30 ?        00:00:00 [ksoftirqd/1]
system_u:system_r:kernel_t:s15:c0.c1023 root 738   2  0 Jun30 ?        00:00:00 [kworker/1:0]
system_u:system_r:kernel_t:s15:c0.c1023 root 739   2  0 Jun30 ?        00:00:00 [kworker/1:0H]
system_u:system_r:kernel_t:s15:c0.c1023 root 743   1  0 Jun30 ?        00:00:00 ./FastRVC
system_u:system_r:kernel_t:s15:c0.c1023 root 747   2  0 Jun30 ?        00:00:00 [ubi_bgt2d]
system_u:system_r:kernel_t:s15:c0.c1023 root 750   2  0 Jun30 ?        00:00:00 [ubifs_bgt2_0]
system_u:system_r:kernel_t:s15:c0.c1023 root 752   2  0 00:00 ?        00:00:00 [kworker/1:1]
system_u:system_r:kernel_t:s15:c0.c1023 root 756   2  0 00:00 ?        00:00:00 [ubi_bgt3d]
system_u:system_r:kernel_t:s15:c0.c1023 root 759   2  0 00:00 ?        00:00:00 [ubifs_bgt3_0]
system_u:system_r:kernel_t:s15:c0.c1023 root 763   2  0 00:00 ?        00:00:00 [ubi_bgt4d]
system_u:system_r:kernel_t:s15:c0.c1023 root 766   2  0 00:00 ?        00:00:00 [ubifs_bgt4_0]
system_u:system_r:kernel_t:s15:c0.c1023 root 838   2  0 00:00 ?        00:00:00 [irq/146-1-0024]
system_u:system_r:kernel_t:s15:c0.c1023 root 901   2  0 00:00 ?        00:00:00 [ubifs_bgt0_0]
system_u:system_r:kernel_t:s15:c0.c1023 root 982   1  0 00:00 ?        00:00:00 auditd
system_u:system_r:kernel_t:s15:c0.c1023 root 985   2  0 00:00 ?        00:00:00 [kauditd]
system_u:system_r:kernel_t:s15:c0.c1023 root 1010  2  0 00:00 ?        00:00:00 [audit_prune_tre]
system_u:system_r:kernel_t:s15:c0.c1023 root 1019  2  0 00:00 ?        00:00:00 [ipv6_addrconf]
system_u:system_r:kernel_t:s15:c0.c1023 root 1047  1  0 00:00 ?        00:00:00 dlt-daemon
system_u:system_r:kernel_t:s15:c0.c1023 root 1048  1  0 00:00 ?        00:00:01 vmf
system_u:system_r:kernel_t:s15:c0.c1023 root 1049  1 10 00:00 ?        00:00:29 ./hmi
system_u:system_r:kernel_t:s15:c0.c1023 root 1050  1  0 00:00 ?        00:00:02 pwr_agent -v -o
system_u:system_r:kernel_t:s15:c0.c1023 root 1051  1  0 00:00 ?        00:00:00 /bin/sh /etc/init.d/rc 5
system_u:system_r:kernel_t:s15:c0.c1023 root 1052  1  0 00:00 ?        00:00:00 /bin/sh /etc/init.d/rc_mxc.S
system_u:system_r:kernel_t:s15:c0.c1023 root 1063  1  0 00:00 ?        00:00:00 /usr/bin/mfid log=5
system_u:system_r:kernel_t:s15:c0.c1023 root 1069 1052  0 00:00 ttymxc3 00:00:00 -sh
system_u:system_r:kernel_t:s15:c0.c1023 infra 1091 1  3 00:00 ?        00:00:10 vgw
system_u:system_r:kernel_t:s15:c0.c1023 root 1095  1  0 00:00 ?        00:00:00 video_manager
system_u:system_r:kernel_t:s15:c0.c1023 root 1116  1  0 00:00 ?        00:00:00 pss
system_u:system_r:kernel_t:s15:c0.c1023 infra 1122 1  0 00:00 ?        00:00:00 network
system_u:system_r:kernel_t:s15:c0.c1023 root 1176  1  0 00:00 ?        00:00:00 configuration
system_u:system_r:kernel_t:s15:c0.c1023 infra 1180 1  0 00:00 ?        00:00:00 vip_agent
system_u:system_r:kernel_t:s15:c0.c1023 root 1198  1  0 00:00 ?        00:00:00 audio_proc
system_u:system_r:kernel_t:s15:c0.c1023 root 1204  1  0 00:00 ?        00:00:00 RVC
system_u:system_r:kernel_t:s15:c0.c1023 root 1508  1  0 00:00 ?        00:00:00 wifi

**Comment by cgzones** [comment]
Process contexts change on *type_transitions*.

> system_u:system_r:kernel_t:s15:c0.c1023 root 1 0 0 Jun30 ? 00:00:02 init [5]

Either the init executable is mislabeled, or your policy is missing `type_transition kernel_t init_exec_t:process init_t;` (one can list all type-transitions with `sesearch -T`).

**Comment by cxdinter** [comment]
> Process contexts change on _type_transitions_.
> 
> > system_u:system_r:kernel_t:s15:c0.c1023 root 1 0 0 Jun30 ? 00:00:02 init [5]
> 
> Either the init executable is mislabeled, or your policy is missing `type_transition kernel_t init_exec_t:process init_t;` (one can list all type-transitions with `sesearch -T`).

 Hi cgzones,
Thanks for your help. 
You are right, I missed to assign label to init executable file, after assgined system_u:system_r:init_exec_t to init executable file in file_contexts. The process contexts changed from kernel_t to init_t.

By the way, I am using the latest refpolicy. And I haven't find type_transition rules for init process. In init.if file, I found below interface. Does this setting caused type transition ? ( from kernel_t to init_t) 

interface(`init_domtrans',`
	gen_require(`
		type init_t, init_exec_t;
	')

	domtrans_pattern($1, init_exec_t, init_t)
')

**Comment by cgzones** [comment]
Yes, `domtrans_pattern` includes a `type_transition`:

https://github.com/SELinuxProject/refpolicy/blob/7f4ffffd7152e4cabea2db01857a48c45bca4bfa/policy/support/misc_patterns.spt#L55-L56

https://github.com/SELinuxProject/refpolicy/blob/7f4ffffd7152e4cabea2db01857a48c45bca4bfa/policy/support/misc_patterns.spt#L41-L44
