### ISSUE TITLE
Update all users of SELinux libraries to current interfaces

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux#34]
libselinux has legacy interfaces and compatibility code that are still in use by some external applications.  We need to identify all such users and update them to use the newer interfaces, e.g. replace calls to matchpathcon interfaces with calls to selabel interfaces, replace most if not all SELinux userspace permission checks (security_compute_av, avc_has_perm) with calls to selinux_check_access, etc.  Then maybe someday we can actually get rid of the legacy stuff upstream.

**Comment by bigon** [comment]
dbus is one of these applications using the old interface, see https://bugs.freedesktop.org/show_bug.cgi?id=92831

**Comment by stephensmalley** [comment]
With the recent changes to libselinux to finally fully remove the hardcoded class and permission definitions (89674c2ff7a86803e3d6eb9c40e227e354d7d397) and update the man pages for userspace policy enforcers (784b029c3ffe0a91390ceb448053ed72fb053b19), I think we've done everything we can upstream to foster migration and most of userspace has already migrated or will soon be forced to do so.  matchpathcon() had its man page updated back in 2015 to deprecate it and encourage people to migrate to using selabel_open/lookup() but there will probably always be some residual users since it is a simpler interface and that's ok.  I'm going to close this issue.

**Comment by bigon** [comment]
Quickly looking in debian archive, I still see some users of these files:

https://codesearch.debian.net/search?q=selinux%2Fav_permissions.h&literal=1
https://codesearch.debian.net/search?q=selinux%2Fflask.h&literal=1&page=1

**Comment by stephensmalley** [comment]
Yep, clearly nothing short of removing the headers will get them to update since they have had ~5 years of build-time #warnings on every include of those headers.

**Comment by stephensmalley** [comment]
Apparently even removing the headers won't fully suffix to remove all hardcoded references to SECCLASS_*. Even though the libselinux header warning messages said to switch to using string_to_security_class() and someone did this correctly for busybox passwd in https://git.busybox.net/busybox/commit/?id=c6f35241b38ea0c9581409efcd83716b74918903, a later commit for busbyox login and runcon re-introduced their own private definitions, https://git.busybox.net/busybox/commit/?id=4ea0ebdd429fe761c1324176b1ac6017248366af.  This will have to get fixed in busybox at some point.
