### ISSUE TITLE
Mismatched parentheses in fcontext man page?

### ISSUE THREAD

**Issue by jw013** [SELinuxProject/selinux#340]
https://github.com/SELinuxProject/selinux/blob/86cdb9f11915187cedee327cb833421374e500d1/python/semanage/semanage-fcontext.8#L6

If I am reading it correctly I think there is an extra `)` after each `FILE_SPEC` occurrence.

**Comment by bachradsusi** [comment]
It looks like you are right.

`man semanage-fcontext`:

    semanage fcontext [-h] [-n] [-N] [-S STORE] [ --add ( -t TYPE -f FTYPE -r RANGE -s SEUSER | -e EQUAL ) FILE_SPEC ) | --delete ( -t TYPE -f FTYPE |  -e EQUAL ) FILE_SPEC ) | --deleteall | --extract | --list [-C] | --modify ( -t TYPE -f FTYPE -r RANGE -s SEUSER | -e EQUAL ) FILE_SPEC ) ]

vs `semanage fcontext -h`:

    semanage fcontext [-h] [-n] [-N] [-S STORE] [ --add ( -t TYPE -f FTYPE -r RANGE -s SEUSER | -e EQUAL ) FILE_SPEC | --delete ( -t TYPE -f FTYPE | -e EQUAL ) FILE_SPEC | --deleteall  | --extract  | --list [-C] | --modify ( -t TYPE -f FTYPE -r RANGE -s SEUSER | -e EQUAL ) FILE_SPEC ]

**Comment by bachradsusi** [comment]
https://lore.kernel.org/selinux/20220302101415.431161-1-plautrba@redhat.com/T/#u

Thanks for the report
