### ISSUE TITLE
How to control tcp server to receive/send messages through a port?

### ISSUE THREAD

**Issue by Hellcatlk** [SELinuxProject/selinux#341]
I want to control tcp server to receive message from port 2402 but prevent it
from sending message to port 2402. 

But It really confused me that only need to give name_bind and name_connect Permissions, 
tcp server can receive/send message through port 2402. 

This doesn't seem to work as expected (since I didn't give read and write permissions).

Kernel version: 4.9.59

**Comment by doverride** [comment]
SELinux knows various way's to do network access control (but many of these way's are not used by default). I will not try to explain them all and I will start by saying that usually its probably better to use the existing kernel netfilter functionality for networking instead.

With that said: SELinux can use used together with netfilter to control access based on packet types. By labeling packets and associating packet labels with protocols, network ports and (ranges of) ip addresses and/or network interrfaces. You can govern who is allowed to "send" and/or "recv" packet types.

https://git.netfilter.org/nftables/tree/files/examples/secmark.nft

The name_bind and name_connect permissions you mention are used to govern who can bind sockets and connect to specified network port type using specified protocol only.

**Comment by doverride** [comment]
https://github.com/SELinuxProject/selinux-notebook/blob/main/src/network_support.md
