### ISSUE TITLE
libsepol: In the scope_index_destroy function，scope->class_perms_len should be set to 0

### ISSUE THREAD

**Issue by lujiev** [SELinuxProject/selinux#344]
In the scope_index_destroy function（ libsepol/src/avrule_block.c ），scope->class_perms_len should be set to 0  after all class_perms_maps are destroyed

**Comment by fishilico** [comment]
> In the scope_index_destroy function（ libsepol/src/avrule_block.c ），scope->class_perms_len should be set to 0 after all class_perms_maps are destroyed

Why? `scope_index_destroy` is only called from `avrule_decl_destroy`, which frees the structure `x` which contains `scope_index_t` fields: https://github.com/SELinuxProject/selinux/blob/0a8c177dacdc1df96ea11bb8aa75e16c4fa82285/libsepol/src/avrule_block.c#L105-L109

If I understand the code correctly, nothing can read `x->required.class_perms_len` or `x->declared.class_perms_len` before `x` is freed.

**Comment by lujiev** [comment]
In current usage, this is ok. However, This is not a good coding specification, and problems may occur if other calling functions are not free 'x' and reused this  scope. Setting to 0 is a good way to avoid this problem, isn't it?
