### ISSUE TITLE
What is the difference between setexeccon_raw and setexeccon?

### ISSUE THREAD

**Issue by duguhaotian** [SELinuxProject/selinux#352]
```
setexeccon() sets the context used for the next [execve](https://www.systutorials.com/docs/linux/man/2-execve/)(2) call. 
NULL can be passed to setexeccon() to reset to the default policy behavior. 
The exec context is automatically reset after the next [execve](https://www.systutorials.com/docs/linux/man/2-execve/)(2), so a program doesn't need to explicitly sanitize it upon startup.

getexeccon_raw() and setexeccon_raw() behave identically to their non-raw counterparts but do not perform context translation
```
setexeccon and setexeccon_raw use to set context before exec,
so what's mean of **do not perform context translation** ?

thanks.

**Comment by duguhaotian** [comment]
>
 
Thank you very much for your reply!

first, “context translation” which is mcstransd translates labels to human readable form?

[mcstransd](https://man7.org/linux/man-pages/man8/mcstransd.8.html) - MCS (Multiple Category System) daemon.  Translates SELinux MCS/MLS labels to human readable form.

second, your python example, show: 

-  setexeccon_raw: don't know label 'SystemLow-SystemHigh' equal to 's0-s0:c0.c1023', so it failed;
- setexeccon: will call mcstransd for translate label 'SystemLow-SystemHigh' to 's0-s0:c0.c1023', so it success;

is it right?

Looking forward to your reply, thanks.

**Comment by duguhaotian** [comment]
> 

third question, i try it, work well on host which no mcstransd service.

```
$ systemctl status mcstransd
Unit mcstransd.service could not be found.

$ python3
Python 3.8.10 (default, May  4 2021, 00:00:00)
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import selinux
>>> selinux.getcon()
[0, 'unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023']
>>> selinux.setexeccon_raw("unconfined_u:unconfined_r:unconfined_t:SystemLow-SystemHigh")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/site-packages/selinux/__init__.py", line 554, in setexeccon_raw
    return _selinux.setexeccon_raw(con)
OSError: [Errno 22] Invalid argument
>>> selinux.setexeccon("unconfined_u:unconfined_r:unconfined_t:SystemLow-SystemHigh")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/site-packages/selinux/__init__.py", line 551, in setexeccon
    return _selinux.setexeccon(con)
OSError: [Errno 22] Invalid argument
>>> selinux.getexeccon()
[0, None]
>>> selinux.getexeccon_raw()
[0, None]
>>> selinux.setexeccon("unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
0
>>> selinux.getexeccon()
[0, 'unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023']
>>> selinux.getexeccon_raw()
[0, 'unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023']
```

**Comment by bachradsusi** [comment]
> 
> Thank you very much for your reply!
> 
> first, “context translation” which is mcstransd translates labels to human readable form?

I'm not sure I understand the question

 
> [mcstransd](https://man7.org/linux/man-pages/man8/mcstransd.8.html) - MCS (Multiple Category System) daemon. Translates SELinux MCS/MLS labels to human readable form.
> 
> second, your python example, show:
> 
>     * setexeccon_raw: don't know label 'SystemLow-SystemHigh' equal to 's0-s0:c0.c1023', so it failed;
> 
>     * setexeccon: will call mcstransd for translate label 'SystemLow-SystemHigh' to 's0-s0:c0.c1023', so it success;
> 
> 
> is it right?

Yes, it's right.

> 
> third, other question: directly do selinux.setexeccon("unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023") is right?

Yes.

**Comment by duguhaotian** [comment]
> 

Thank you very much for your reply!

first question is 
do  “context translation” means：use mcstransd translates labels to human readable form?

**Comment by bachradsusi** [comment]
Yes, that's correct. mcstransd translates SELinux MCS/MLS labels to human readable form too e.g. 

~~~
[root@P1 ~]# id -Z
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[root@P1 ~]# systemctl start mcstransd
[root@P1 ~]# id -Z
unconfined_u:unconfined_r:unconfined_t:SystemLow-SystemHigh
~~~

**Comment by duguhaotian** [comment]
> Yes, that's correct. mcstransd translates SELinux MCS/MLS labels to human readable form too e.g.
> 
> ```
> [root@P1 ~]# id -Z
> unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
> [root@P1 ~]# systemctl start mcstransd
> [root@P1 ~]# id -Z
> unconfined_u:unconfined_r:unconfined_t:SystemLow-SystemHigh
> ```

thanks very much.
