### ISSUE TITLE
Selinux for ubuntu

### ISSUE THREAD

**Issue by badr-badri** [SELinuxProject/selinux#38]
Hello,
Can  you please indicates me how to install correctly selinux on ubuntu 16.10. I can compile it correctly from the source but then I don't how how to create a the configuration file with the minimal policy so I can have a correct running system. 
Thanks in advance

**Comment by stephensmalley** [comment]
There should be a Debian package that contains a SELinux policy, or alternatively you can always build the refpolicy from source.  The kind of question should be asked on the upstream selinux mailing list or the Debian selinux mailing list, not here.

**Comment by stephensmalley** [comment]
This may be helpful to you:
https://wiki.debian.org/SELinux
