### ISSUE TITLE
sestatus: show whether neverallow rules checking is enabled

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/selinux#39]
It would be nice, if sestatus shows whether neverallow rules are checked

**Comment by stephensmalley** [comment]
Not sure it is worthwhile or fits with the other sestatus information, which is all about SELinux runtime information available via libselinux.  In contrast, neverallow checking is controlled by semanage.conf, only read by libsemanage and not presently exported via any API.

**Comment by cgzones** [comment]
Yeah, i see; maybe seinfo might be a better place?
