### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by freedom1b2830** [SELinuxProject/selinux#390]
exist in /usr/lib/python3.10/site-packages/sepolgen
no exist in /usr/lib/python3.11/site-packages/sepolgen
sepolgen is given as an example

**Comment by freedom1b2830** [comment]
@bachradsusi  And how will this help me?
I tried with different installation paths:
export DESTDIR=/home/suduuser/SE
export DESTDIR=/

./semanage
```
Traceback (most recent call last):
   File "/home/suduuser/SE/usr/sbin/./semanage", line 29, in <module>
     import seobject
   File "/usr/lib/python3.11/site-packages/seobject.py", line 33, in <module>
     import sepolicy
   File "/usr/lib/python3.11/site-packages/sepolicy/__init__.py", line 15, in <module>
     from settools.boolquery import BoolQuery
ModuleNotFoundError: No module named 'setools'
```

**Comment by bachradsusi** [comment]
I don't know what is your system, how did you install selinux tools, and lot of other important details.

```
ModuleNotFoundError: No module named 'setools'
```

means that there's missing python3 setools libraries. I guess you need to rebuild it as well - https://github.com/SELinuxProject/setools

**Comment by freedom1b2830** [comment]
I have an Arch Linux distribution
python3.10 moved  to python3.11
installed libraries refer to 3.10
package maintainer for arch linux not yet building on 3.11 https://github.com/archlinuxhardened/selinux/issues/117
- rebuilding https://github.com/SELinuxProject/setools helped me
