### ISSUE TITLE
bad gpg signature

### ISSUE THREAD

**Issue by yardenac** [SELinuxProject/selinux#393]
When trying to build [libselinux](https://aur.archlinux.org/packages/libselinux)/[libsemanage](https://aur.archlinux.org/packages/libsemanage)/etc from AUR, I get errors because of this:

```
$ gzip -c -d -f libselinux-3.5.tar.gz | gpg --verbose --batch --status-file /dev/stdout --verify libselinux-3.5.tar.gz.asc -
gpg: enabled compatibility flags:
gpg: armor header: Version: GnuPG v2
[GNUPG:] NEWSIG
gpg: Signature made Thu 23 Feb 2023 05:34:21 AM PST
gpg:                using RSA key E162DEAD1CCDD113F04B3D492BBED9CB1A68EF55
gpg: Note: signatures using the SHA1 algorithm are rejected
gpg: using subkey 2BBED9CB1A68EF55 instead of primary key 7EF137EC935B0EAF
[GNUPG:] KEY_CONSIDERED 63191CE94183098689CAB8DB7EF137EC935B0EAF 0
gpg: using subkey 2BBED9CB1A68EF55 instead of primary key 7EF137EC935B0EAF
[GNUPG:] KEY_CONSIDERED 63191CE94183098689CAB8DB7EF137EC935B0EAF 0
gpg: using pgp trust model
[GNUPG:] BADSIG 2BBED9CB1A68EF55 Jason Zaman <jasonzaman@gmail.com>
gpg: BAD signature from "Jason Zaman <jasonzaman@gmail.com>" [unknown]
gpg: binary signature, digest algorithm SHA512, key algorithm rsa4096
[GNUPG:] FAILURE gpg-exit 33554433

$ gpg --verbose --recv-keys 63191CE94183098689CAB8DB7EF137EC935B0EAF
gpg: enabled compatibility flags:
gpg: data source: https://162.213.33.9:443
gpg: armor header: Comment: Hostname:
gpg: armor header: Version: Hockeypuck 2.1.0-222-g25248d4
gpg: key 7EF137EC935B0EAF: number of dropped non-self-signatures: 58
gpg: pub  rsa4096/7EF137EC935B0EAF 2014-03-26  Jason Zaman <jasonzaman@gmail.com>
gpg: Note: signatures using the SHA1 algorithm are rejected
gpg: key 7EF137EC935B0EAF: 6 bad signatures
gpg: key 7EF137EC935B0EAF/3C5B5F43DE9F01FC: invalid subkey binding
gpg: key 7EF137EC935B0EAF/2BBED9CB1A68EF55: invalid subkey binding
gpg: key 7EF137EC935B0EAF: "Jason Zaman <jasonzaman@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Maybe @perfinion should check their keys and sign these again?

**Comment by bachradsusi** [comment]
```
gpg2 --verify libselinux-3.5.tar.gz.asc libselinux-3.5.tar.gz
gpg: Signature made Thu 23 Feb 2023 02:34:21 PM CET
gpg:                using RSA key E162DEAD1CCDD113F04B3D492BBED9CB1A68EF55
gpg: Good signature from "Jason Zaman <jasonzaman@gmail.com>" [unknown]
gpg:                 aka "Jason Zaman (Gentoo Developer) <perfinion@gentoo.org>" [unknown]
gpg:                 aka "Jason Zaman <jason@perfinion.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6319 1CE9 4183 0986 89CA  B8DB 7EF1 37EC 935B 0EAF
     Subkey fingerprint: E162 DEAD 1CCD D113 F04B  3D49 2BBE D9CB 1A68 EF55

```

**Comment by yardenac** [comment]
Thank you @bachradsusi, it seems my errors were caused by having `weak-digest sha1` in gpg.conf. Sorry for the noise.

**Comment by perfinion** [comment]
> Thank you @bachradsusi, it seems my errors were caused by having `weak-digest sha1` in gpg.conf. Sorry for the noise.

Oh interesting. I will look into that for the next release then and sign with better digests.
Glad it wasn't a problem with my key, but definitely thanks for the bug report!

**Comment by ninetailedtori** [comment]
Err...not sure who or *what* signed the recent build, it is unknown to any keyserver. "68D21823342A13683AEB3E4EFB4C685B5DC1C13E", which is not "63191CE94183098689CAB8DB7EF137EC935B0EAF" on all current keyservers.

**Comment by fishilico** [comment]
> Err...not sure who or what signed the recent build, it is unknown to any keyserver. "68D21823342A13683AEB3E4EFB4C685B5DC1C13E". Apparently it belongs to Petr Lautrbach [lautrbach@redhat.com](mailto:lautrbach@redhat.com), but it's not uploaded anywhere. Perhaps he forgot to refresh his key.

@ninetailedtori When I updated the packages for Arch Linux (in the AUR), I used the public keys from https://github.com/bachradsusi.gpg . This file contains multiple public key, including 68D21823342A13683AEB3E4EFB4C685B5DC1C13E. To make things simpler, I copied this file to [`keys/pgp/68D21823342A13683AEB3E4EFB4C685B5DC1C13E.asc`](https://github.com/archlinuxhardened/selinux/blob/master/libsepol/keys/pgp/68D21823342A13683AEB3E4EFB4C685B5DC1C13E.asc) but it seems you failed to find this key.

**Comment by ninetailedtori** [comment]
Yeah, unsure why. I did a full refresh, even manually looked it up on the ubuntu keyserver yesterday...perhaps it was just desynced for a bit? It's completely refreshed fine now for me, even with the manual lookup all is fine :)
