### ISSUE TITLE
checkpolicy compilation error

### ISSUE THREAD

**Issue by AlexeiKharchev** [SELinuxProject/selinux#395]
# briefly:
I cannot build selinux 3.5 with shared libraries on Linux Mint, so I tried to make it step by step 
wget -O selinix-3.5.tar.gz "https://github.com/SELinuxProject/selinux/archive/refs/tags/3.5.tar.gz"
tar xvf selinix-3.5.tar.gz && cd selinix-3.5
installdir=/tools/selinux-3.5 - I use intermediate folder for convenience.
1)  Compiling libsepol and installing to /tools/selinux-3.5, linking => /usr/local/lib
2)  Compiling libselinux and installing to /tools/selinux-3.5, linking => /usr/local/lib
3)  Compiling libsemanage and installing to /tools/selinux-3.5, linking => /usr/local/lib
4)  Compiling checkpolicy  - error inspite of there is -lsepol in  checkpolicy/Makefile and there is libsepol.so in /usr/local/lib

detailed information
1. Compiling libsepol
$  pushd libsepol
$  make
\#  preparing for installing to /tools/selinux-3.5
$  sed -i 's|\$[(]DESTDIR[)]|$(PREFIX)|g' src/Makefile
$  sed -i 's|\(^LIBDIR ?= \)\$[(]PREFIX[)]|\1|' src/Makefile
$  sed -i 's|^BINDIR ?= \$[(]DESTDIR[)]|BINDIR ?= $(PREFIX)|' utils/Makefile
$  make PREFIX="$installdir" install
\#  removing static library
$  [[ -f "$installdir"/lib/libsepol.a ]] && rm -fv "$installdir"/lib/libsepol.a
\#  adding .la file to /tools/selinux-3.5/lib
$  ./prepare-la --library="$installdir/lib" --version="2.0" 'libsepol.so.2'
\#  changing libsepol.pc to /usr/local
$  sed -i 's|/usr/|${prefix}/|g' "$installdir"/lib/pkgconfig/libsepol.pc
$  sed -i 's|^\(prefix=\).*$|\1/usr/local|' "$installdir"/lib/pkgconfig/libsepol.pc
\#  making links for built libraries to /usr/local/lib
$  sudo ln -sfv "$installdir"/lib/libsepol.* /usr/local/lib/
$  sudo ln -sfv "$installdir"/lib/pkgconfig/libsepol.pc /usr/local/lib/pkgconfig/
\#  
$  sed -i 's|^\(LIBSEPOL :=\) .*$|\1 -lsepol|' tests/Makefile
popd

2. Compiling libselinux
pushd libselinux
$  make
\#  preparing for installing to /tools/selinux-3.5
$  sed -i 's|\$[(]DESTDIR[)]|$(PREFIX)|g' src/Makefile
$  sed -i 's|\(^LIBDIR ?= \)\$[(]PREFIX[)]|\1|' src/Makefile
$  sed -i 's|^SBINDIR ?= \$[(]DESTDIR[)]|SBINDIR ?= $(PREFIX)|' utils/Makefile
$  make PREFIX="$installdir" install
\#  removing static library
$  [[ -f "$installdir"/lib/libselinux.a ]] && rm -fv "$installdir"/lib/libselinux.a
\#  changing libselinux.pc to /usr/local
$  sed -i 's|/usr/|${prefix}/|g' "$installdir"/lib/pkgconfig/libselinux.pc
$  sed -i 's|^\(prefix=\).*$|\1/usr/local|' "$installdir"/lib/pkgconfig/libselinux.pc
\#  adding .la file to /tools/selinux-3.5
$  prepare-la --library="$installdir/lib" --version="1.0" 'libselinux.so.1'
\#  making links for built libraries to /usr/local/lib
$  sudo ln -sfv "$installdir"/lib/libselinux.* /usr/local/lib/
$  sudo ln -sfv "$installdir"/lib/pkgconfig/libselinux.pc /usr/local/lib/pkgconfig/
popd

3. Compiling libsemanage
pushd libsemanage
\#  there is no -lpcre in src/Makefile
$  sed -i 's/\(-lsepol -laudit -lselinux -lbz2\)/\1 -lpcre2-posix/' src/Makefile
$  make
$  make PREFIX="$installdir" install
$  [[ -f "$installdir"/lib/libsemanage.a ]] && rm -fv "$installdir"/lib/libsemanage.a
\#  changing libsemanage.pc to /usr/local
$  sed -i 's|/usr/|${prefix}/|g' "$installdir"/lib/pkgconfig/libsemanage.pc
$  sed -i 's|^\(prefix=\).*$|\1/usr/local|' "$installdir"/lib/pkgconfig/libsemanage.pc
// there is no -lpcre in .pc file
$  sed -i 's/ -lbz2/ -lbz2 -lpcre2-posix/' "$installdir"/lib/pkgconfig/libsemanage.pc
\#  adding .la file to /tools/selinux-3.5
$  ./prepare-la --library="$installdir/lib" --version="2.0" 'libsemanage.so.2'
$  sed -i "s|^dependency_libs=''|dependency_libs=' -L/usr/local/lib -lbz2 -lpcre2-posix'|" "$installdir"/lib/libsemanage.la
\#  making links for built libraries to /usr/local/lib
$  sudo ln -sfv "$installdir"/lib/libsemanage.* /usr/local/lib/
$  sudo ln -sfv "$installdir"/lib/pkgconfig/libsemanage.pc /usr/local/lib/pkgconfig/
popd

\# linking $installdir/include directory to /usr/local/include
for d in selinux semanage sepol; do
  sudo rm -fv /usr/local/include/$d
  sudo ln -sfv $installdir/include/$d /usr/local/include/
done

\# It seems to mee, here everything is ok, but next step is disapponting
4. Compiling checkpolicy
pushd checkpolicy
$  make

# error:
$  cc -g -Wall -Werror -Wshadow -O2 -fno-strict-aliasing -fPIC -o checkpolicy y.tab.o lex.yy.o queue.o module_compiler.o parse_util.o policy_define.o checkpolicy.o  -L/usr/local/lib -lsepol
/usr/local/bin/ld: checkpolicy.o: in function «main»:
/home/alexei/build/selinux-3.5/checkpolicy/checkpolicy.c:529: undefined reference to «sepol_set_policydb»
/usr/local/bin/ld: /home/alexei/build/selinux-3.5/checkpolicy/checkpolicy.c:530: undefined reference to «sepol_set_sidtab»
/usr/local/bin/ld: /home/alexei/build/selinux-3.5/checkpolicy/checkpolicy.c:604: undefined reference to «policydb_init»

**Comment by AlexeiKharchev** [comment]
my system: 
[my_system.txt](https://github.com/SELinuxProject/selinux/files/11592029/my_system.txt)

**Comment by AlexeiKharchev** [comment]
my LD_LIBRARY_PATH is correct:
alexei@Aspire:~$ echo $LD_LIBRARY_PATH 
/usr/local/lib:/usr/local/lib/x86_64-linux-gnu:/home/alexei/.local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib

I see my libraries installed:
alexei@Aspire:~$ ls -la /usr/local/lib/libse*
lrwxrwxrwx 1 root root 41 мая  7 14:32 /usr/local/lib/libseccomp.la -> /tools/libseccomp-2.5.4/lib/libseccomp.la
lrwxrwxrwx 1 root root 47 мая  7 14:32 /usr/local/lib/libseccomp.so -> /tools/libseccomp-2.5.4/lib/libseccomp.so.2.5.4
lrwxrwxrwx 1 root root 47 мая  7 14:32 /usr/local/lib/libseccomp.so.2 -> /tools/libseccomp-2.5.4/lib/libseccomp.so.2.5.4
lrwxrwxrwx 1 root root 47 мая  7 14:32 /usr/local/lib/libseccomp.so.2.5.4 -> /tools/libseccomp-2.5.4/lib/libseccomp.so.2.5.4
lrwxrwxrwx 1 root root 34 мая 28 16:49 /usr/local/lib/libsectool.a -> /tools/nss-3.89.1/lib/libsectool.a
lrwxrwxrwx 1 root root 36 мая 29 13:59 /usr/local/lib/libselinux.la -> /tools/selinux-3.5/lib/libselinux.la
lrwxrwxrwx 1 root root 36 мая 29 13:59 /usr/local/lib/libselinux.so -> /tools/selinux-3.5/lib/libselinux.so
lrwxrwxrwx 1 root root 38 мая 29 13:59 /usr/local/lib/libselinux.so.1 -> /tools/selinux-3.5/lib/libselinux.so.1
lrwxrwxrwx 1 root root 37 мая 29 14:21 /usr/local/lib/libsemanage.la -> /tools/selinux-3.5/lib/libsemanage.la
lrwxrwxrwx 1 root root 37 мая 29 14:21 /usr/local/lib/libsemanage.so -> /tools/selinux-3.5/lib/libsemanage.so
lrwxrwxrwx 1 root root 39 мая 29 14:21 /usr/local/lib/libsemanage.so.2 -> /tools/selinux-3.5/lib/libsemanage.so.2
lrwxrwxrwx 1 root root 34 мая 29 13:52 /usr/local/lib/libsepol.la -> /tools/selinux-3.5/lib/libsepol.la
lrwxrwxrwx 1 root root 34 мая 29 13:52 /usr/local/lib/libsepol.so -> /tools/selinux-3.5/lib/libsepol.so
lrwxrwxrwx 1 root root 36 мая 29 13:52 /usr/local/lib/libsepol.so.2 -> /tools/selinux-3.5/lib/libsepol.so.2

**Comment by AlexeiKharchev** [comment]
alexei@Aspire:~$ ldd /usr/local/lib/libsepol.so
	linux-vdso.so.1 (0x00007fff55bdc000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f053a1c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f053a471000)

**Comment by bachradsusi** [comment]
You could simply use `DESTDIR` for that, see *README.md*

~~~
$ wget -O selinux-3.5.tar.gz "https://github.com/SELinuxProject/selinux/archive/refs/tags/3.5.tar.gz"
$ tar xvf selinux-3.5.tar.gz && cd selinux-3.5
$ make DESTDIR=/home/bachradsusi/build/checkpolicy install
...
make[1]: Entering directory '/home/bachradsusi/tmp/selinux-3.5/checkpolicy'
cc -O2 -Werror -Wall -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wnull-dereference -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -fno-common -I/home/bachradsusi/build/checkpolicy/usr/include -o checkpolicy y.tab.o lex.yy.o queue.o module_compiler.o parse_util.o policy_define.o checkpolicy.o /home/bachradsusi/build/checkpolicy/usr/lib/libsepol.a -L/home/bachradsusi/build/checkpolicy/usr/lib -L/home/bachradsusi/build/checkpolicy/usr/lib 
cc -O2 -Werror -Wall -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wnull-dereference -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -fno-common -I/home/bachradsusi/build/checkpolicy/usr/include -o checkmodule y.tab.o lex.yy.o queue.o module_compiler.o parse_util.o policy_define.o checkmodule.o /home/bachradsusi/build/checkpolicy/usr/lib/libsepol.a -L/home/bachradsusi/build/checkpolicy/usr/lib -L/home/bachradsusi/build/checkpolicy/usr/lib 
...

$ DESTDIR=/home/bachradsusi/build/checkpolicy source scripts/env_use_destdir   

$ which checkpolicy  
/home/bachradsusi/build/checkpolicy/usr/bin/checkpolicy

$ /home/bachradsusi/build/checkpolicy/usr/bin/checkpolicy --help      
usage:  /home/bachradsusi/build/checkpolicy/usr/bin/checkpolicy [-b[F]] [-C] [-d] [-U handle_unknown (allow,deny,reject)] [-M] [-c policyvers (15-33)] [-o output_file|-] [-S] [-O] [-t target_platform (selinux,xen)] [-E] [-V] [input_file]
~~~
