### ISSUE TITLE
How Do I Select a Proper Number of Threads for Labeling?

### ISSUE THREAD

**Issue by zhangg05283106** [SELinuxProject/selinux#407]
hi,
As selinux_restorecon_parallel function shows that multiple threads can be selected for performance optimization,  is there some guidance on how to select the right number of threads? 
and other two questions,
1. Are there any dependencies on resources? 
2. Does the community have reference data for optimizing the multi-thread tagging time? For example, to tag 1000000 files, what are the time required for single-thread and multi-thread?
Thank you very much.

**Comment by bachradsusi** [comment]
You could use 0 which will use as many threads as there are available CPU cores.  I don't think there's a general guidance - it depends on used hardware. But there are some numbers in the commit which introduced this feature -

https://github.com/SELinuxProject/selinux/commit/93902fc8340f8a6ee5ba69ccb150d47918aad226
