### ISSUE TITLE
File "/usr/lib/python-exec/python3.4/sepolicy", line 265

### ISSUE THREAD

**Issue by FIOpwK** [SELinuxProject/selinux#41]
Running the following command on Gentoo Linux profile=hardened/linux/amd64/selinux  kernel= linux-4.4.39-gentoo, (kernel=linux-4.7.10-hardened)*  with python version Python 3.4.5, produces syntax error in code found in: 

File "/usr/lib/python-exec/python3.4/sepolicy", line 265

Syntax Discription: print "\n" + bold_start + "%s: %s %s" % (src, protocol, perm) + bold_end

Print commands in sepolicy.py: https://dpaste.de/7ttM

Command: **sepolicy** (with or without additional options syntax error is produced)

package name: sys-apps/policycoreutils

**Comment by FIOpwK** [comment]
[I] sys-apps/policycoreutils
	Available Versions:	2.6 2.5 2.4-r2 2.4-r1 2.4 
	Last Installed Ver:	2.6(Sun 25 Dec 2016 11:01:22 AM EST)
	Homepage:		https://github.com/SELinuxProject/selinux/wiki
	Description:		SELinux core utilities
	Matched Files:		/usr/share/bash-completion/completions/sepolicy; /usr/lib/python-exec/python3.4/sepolicy; /usr/lib/python-exec/python3.3/sepolicy; /usr/lib/python-exec/python2.7/sepolicy; /usr/bin/sepolicy;

**Comment by stephensmalley** [comment]
Appears to already have been addressed upstream AFAICT.
