### ISSUE TITLE
Should ignoredirs apply to all subdirectories?

### ISSUE THREAD

**Issue by opoplawski** [SELinuxProject/selinux#433]
Fedora ships a semanage.conf with:
```
ignoredirs=/root;/bin;/boot;/dev;/etc;/lib;/lib64;/proc;/run;/sbin;/sys;/tmp;/usr;/var
```
From this commit:
```
commit 0ae5e5f70c6c7ab13ea765084c27fc87106345a0
Author: Petr Lautrbach <plautrba@redhat.com>
Date:   Fri Dec 18 17:24:10 2020 +0100

    semanage.conf - expand list of ignoredirs
    
    It should prevent problems with wrong labels on directories in / after
    commands like:
    
        # useradd -Z unconfined_u -d /var test
    
        # matchpathcon /var
        /var    unconfined_u:object_r:user_home_dir_t:s0
```
However, this does not help with users with subdirectories in /var like amandabackup (/var/lib/amanda).  It feels like the intent is to perhaps cover this, but it does not.   I'm looking for some clarification here.

The current check is a straight strcmp() - https://github.com/SELinuxProject/selinux/blob/main/libsemanage/src/genhomedircon.c#L175

**Comment by bachradsusi** [comment]
Please share more information about your issue.

`ignoredirs` is list of directories which should not be labeled as user home dirs - `user_home_dir_t`.  i.e. if there's a user with a shell from `/etc/shell` and home set to `/var`, SELinux would not relabel `/var` to `user_home_dir_t`. It does not mean that any home subdirectory in `/var` would not be relabeled.

Also the default `semanage.conf` contains the following lines:

~~~
# usepasswd check tells semanage to scan all pass word records for home directories
# and setup the labeling correctly. If this is turned off, SELinux will label only /home
# and home directories of users with SELinux login mappings defined, see
# semanage login -l for the list of such users.
# If you want to use a different home directory, you will need to use semanage fcontext command.
# For example, if you had home dirs in /althome directory you would have to execute
# semanage fcontext -a -e /home /althome
usepasswd=False
~~~

So  `amandabackup`  user with home `/var/lib/amanda` should not affect SELinux labeling unless there's an SELinux login entry with `amandabackup` user.

**Comment by bachradsusi** [comment]
~~~
root@fedora:~# grep amandabackup /etc/passwd
amandabackup:x:33:6:Amanda user:/var/lib/amanda:/bin/bash

root@fedora:~# semanage fcontext -l | grep '/var/lib/amanda '
/var/lib/amanda                                    directory          system_u:object_r:amanda_var_lib_t:s0 

root@fedora:~# matchpathcon /var/lib/amanda/
/var/lib/amanda system_u:object_r:amanda_var_lib_t:s0

root@fedora:~# semanage login -a -s staff_u amandabackup

root@fedora:~# semanage login -l -C
amandabackup         staff_u              s0-s0:c0.c1023       *

root@fedora:~# semanage fcontext -l | grep '/var/lib/amanda '
/var/lib/amanda                                    directory          staff_u:object_r:user_home_dir_t:s0 
/var/lib/amanda                                    symbolic link      staff_u:object_r:user_home_dir_t:s0 

root@fedora:~# matchpathcon /var/lib/amanda/
/var/lib/amanda staff_u:object_r:user_home_dir_t:s0

~~~

**Comment by bachradsusi** [comment]
Given that you modify the user you could create the amandabackup user with home outside /var/lib/amanda as a workaround.

The amanda package itself does not add SELinux login mapping for the user so the default should be fine.

**Comment by opoplawski** [comment]
That's a possibility, though not sure what else that would break.  In any case, I'll close this.  Thanks for the responses.
