### ISSUE TITLE
Regarding a mlsconstrain issue

### ISSUE THREAD

**Issue by kloud-byun** [SELinuxProject/selinux#454]
Hi, I wasn't sure where to ask questions regarding SELinux. I couldn't find any live, or on-going community. And I'm just taking a shot, hoping someone would read and respond to this hopefully;

But I'm running a project that utilizes rootless podman containers, in my RHEL9.2 machine.
I am trying to run the containers on MLS Enforcing mode (or Targeted with Multi Category Security, Enforcing if MLS doesn't work), but I keep facing denials such as:
```
type=AVC msg=audit(XXXX): avc: denied { recv } for pid=31368 comm="curl" saddr=192.168.99.2 src=54380 daddr=192.168.99.2 dest=9099 netif=lo scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:object_r:netlabel_peer_t:s0:c1 tclass=peer permissive=1
```

(I'm supposed to launch a container w/ MLS level of `s0:c1` via curling the VM's systemd's socket that will eventually trigger the python app to launch the containers). So I believe that is why I'm receiving `s0:c1` as my `tcontext`, and `s0` as my `scontext` (coming from Systemd I'm assuming). If I run `audit2allow` on this, I get something like:
```
#!!!! This avc is a constraint violation.  You would need to modify the attributes of either the source or target types to allow this access.
#Constraint rule: 
#	mlsconstrain peer { recv } ((l1 dom l2 -Fail-)  or (t1 != mcs_constrained_type -Fail-)  and (t2 != mcs_constrained_type -Fail-) ); Constraint DENIED
```

so I can see that `s0` cannot dominate `s0:c1` right now, and both types ARE `mcs_constrained_type` which I do not know how to get rid of.

Are there any references on how to go about solving these mlsconstrain issues by any chance? Thank you so much in advance.

**Comment by bachradsusi** [comment]
There's live and ongoing community on selinux@vger.kernel.org mailing list - https://lore.kernel.org/selinux/

**Comment by kloud-byun** [comment]
> There's live and ongoing community on [selinux@vger.kernel.org](mailto:selinux@vger.kernel.org) mailing list - https://lore.kernel.org/selinux/

Thank you so much, I'll go ahead and send the inquiry to the referred email. I appreciate it!
