### ISSUE TITLE
Policy Store Migration service fails to start without further comment

### ISSUE THREAD

**Issue by ErichHartmann** [SELinuxProject/selinux#53]
selinux-policy-migrate-local-changes@targeted.service fails without further notification of the nature of the error. As far as I can tell, the red hat SELinux User's and Administrator's Guide does not mention this migration service.

OS: Centos7 3.10.0-514.6.1.el7.x86_64

EDIT: attempting to run /usr/libexec/selinux/selinux-policy-migrate-local-changes.sh directly results in...

> /usr/libexec/selinux/selinux-policy-migrate-local-changes.sh: line 58: /etc/selinux//modules/active/README.migrated: No such file or directory

Service error messages:

> selinux-policy-migrate-local-changes@targeted.service - Migrate local SELinux policy changes from the old store structure to the new structure
>    Loaded: loaded (/usr/lib/systemd/system/basic.target.wants/../selinux-policy-migrate-local-changes@.service; static; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Tue 2017-04-18 23:11:25 UTC; 41min ago
>  Main PID: 589 (code=exited, status=208/STDIN)
>

> Apr 18 23:11:25 user5411-centos7 systemd[1]: Starting Migrate local SELinux policy changes from the old store structure to the new structure...
> Apr 18 23:11:25 user5411-centos7 systemd[589]: Failed at step STDIN spawning /usr/libexec/selinux/selinux-policy-migrate-local-changes.sh: Inappropriate ioctl for device
> Apr 18 23:11:25 user5411-centos7 systemd[1]: selinux-policy-migrate-local-changes@targeted.service: main process exited, code=exited, status=208/STDIN
> Apr 18 23:11:25 user5411-centos7 systemd[1]: Failed to start Migrate local SELinux policy changes from the old store structure to the new structure.
> Apr 18 23:11:25 user5411-centos7 systemd[1]: Unit selinux-policy-migrate-local-changes@targeted.service entered failed state.
> Apr 18 23:11:25 user5411-centos7 systemd[1]: selinux-policy-migrate-local-changes@targeted.service failed.
>

There is no /var/lib/selinux directory on the system... a likely component of the error.

> 
> /etc/selinux
> ├── tmp
> ├── targeted
> │   ├── seusers
> │   ├── setrans.conf
> │   ├── semanage.trans.LOCK
> │   ├── semanage.read.LOCK
> │   ├── policy
> │   │   └── policy.30
> │   ├── modules
> │   │   └── active
> │   │       └── modules
> │   ├── logins
> │   ├── contexts
> │   │   ├── x_contexts
> │   │   ├── virtual_image_context
> │   │   ├── virtual_domain_context
> │   │   ├── users
> │   │   │   ├── xguest_u
> │   │   │   ├── user_u
> │   │   │   ├── unconfined_u
> │   │   │   ├── sysadm_u
> │   │   │   ├── staff_u
> │   │   │   ├── root
> │   │   │   └── guest_u
> │   │   ├── userhelper_context
> │   │   ├── systemd_contexts
> │   │   ├── snapperd_contexts
> │   │   ├── sepgsql_contexts
> │   │   ├── securetty_types
> │   │   ├── removable_context
> │   │   ├── lxc_contexts
> │   │   ├── initrc_context
> │   │   ├── files
> │   │   │   ├── media
> │   │   │   ├── file_contexts.subs_dist
> │   │   │   ├── file_contexts.subs
> │   │   │   ├── file_contexts.homedirs.bin
> │   │   │   ├── file_contexts.homedirs
> │   │   │   ├── file_contexts.bin
> │   │   │   └── file_contexts
> │   │   ├── failsafe_context
> │   │   ├── default_type
> │   │   ├── default_contexts
> │   │   ├── dbus_contexts
> │   │   └── customizable_types
> │   ├── booleans.subs_dist
> │   └── active [error opening dir]
> ├── semanage.conf
> ├── final [error opening dir]
> └── config
>

**Comment by bachradsusi** [comment]
Hello,

please report your issue directly to Red Hat bugzilla using the following link: 
https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=selinux-policy  

selinux-policy-migrate-local-changes@.service is Red Hat downstream service which helps migrate systems from RHEL-7.2 with SELinux Userspace < 2.4 to RHEL-7.3 with Userspace > 2.4. There's no such service in this repository.

**Comment by ErichHartmann** [comment]
@bachradsusi I apologize. There is no documentation and your wiki...

https://github.com/SELinuxProject/selinux/wiki/Policy-Store-Migration

led me to believe this was somehow your service.
