### ISSUE TITLE
sepolicy calls segenxml.py with python2

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/selinux#61]
Hi,

It seems that in the interface.py file of sepolicy, the code calls segenxml.py from the refpolicy with python2.

Looking at segenxml.py it seems that the shebang is defined with python3, I guess that the invocation should use python3 as well

https://github.com/SELinuxProject/selinux/blob/master/python/sepolicy/sepolicy/interface.py#L201

**Comment by stephensmalley** [comment]
There is likely the broader question of whether selinux userspace should be converted entirely to python3.  I think Fedora has done this for some time in their patches.  Probably a question for the mailing list.
