### ISSUE TITLE
Compatibility with GCC < 4.7 and ATOMICS

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [SELinuxProject/selinux#97]
https://github.com/SELinuxProject/selinux/blob/f6e7613bd3196639edc9ec3cc6ca3e84a6960fcd/libselinux/src/label_file.h#L355

Would an approach using sync's like the suggestion here be viable?
http://buildroot-busybox.2317881.n4.nabble.com/PATCH-docs-manual-gcc-4-4-is-the-lowest-we-are-known-to-work-with-tp200075p200254.html

**Comment by williamcroberts** [comment]
Well, albeit slower, the use of atomics there could be removed and the existing mutex (spec->regex_compiled) be used within the mutex. Then their are no atomics. Not sure how badly that would affct performance, but I would wager it won't be noticeable.

**Comment by slightlyunconventional** [comment]
Normal (non-atomic) accesses to 'spec->regex_compiled' would have equivalent effects to today's code.

Atomic accesses would only be needed if you were trying to implement thread-safe algorithm without any locks. But you're not; you're just doing a first pass "should we even attempt to lock?" filter. In the current code, the pre-lock accesses to regex_compiled will race whether atomic or not; it's the mutex that ensures safety.

**Comment by stephensmalley** [comment]
Yes, I questioned the need for atomics in the original patch.  At the time, the author of the patch said "I was thinking of that, but I figure I don't want to fix a multi threading issue by introducing a potential / even more subtle multi threading issue by relying on the compiler / architecture to do what I want.  The atomics make it explicit that if compile_regex() returns success, that the regex is ready to be used, which isn't necessarily a guarantee that can be made across architectures without them."
If that's a bogus argument, then I'm open to a patch to get rid of it, but probably ought to include the original author on that as well.

**Comment by slightlyunconventional** [comment]
I'm very very skeptical (see in particular [POSIX 4.12 "Memory Synchronization"](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_12)), but as an incremental improvement I'll just address the build issue.

**Comment by slightlyunconventional** [comment]
I guess I'll submit to selinux@tycho.nsa.gov too, but that list doesn't seem to have public archives so I wouldn't be able to include a link here.

[0001-Fix-build-break-around-__atomic_-with-GCC-4.7.patch.txt](https://github.com/SELinuxProject/selinux/files/2284464/0001-Fix-build-break-around-__atomic_-with-GCC-4.7.patch.txt)
