### ISSUE TITLE
lgtm.com does not check c code

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/selinux#98]
It seems https://lgtm.com/projects/g/SELinuxProject/selinux/ does not check the c code.
I am not too familiar with the service, but maybe a configuration file is needed.

**Comment by stephensmalley** [comment]
I'm not familiar with lgtm, so i can't speak to that.  Certainly willing to take a patch to include a config in the selinux userspace tree, just like the travis config, if that helps with automated checking.
